### ISSUE TITLE
Optimize height of placeholder maybe using the preview image and show CE title?

### ISSUE THREAD

**Issue by hilburger** [ErHaWeb/klaro_consent_manager#3]
Hi Eric! 

Awesome work - this is one of the most useful extensions of 2023 :-)

**My "problem" no.1:**
I have a little problem trying to avoid skipping of the layout due to the dynamic height of the placeholder, especially with (Youtube-)videos.  
You know the phenomenon for sure that as soon as you accept the layout gets into place und that looks pretty disturbing from an UX point of view:
<img width="1058" alt="image" src="https://github.com/ErHaWeb/klaro_consent_manager/assets/2393228/e8b49768-7285-4cc8-8de8-635d42530a44">

looks like this after accepting: 
<img width="1076" alt="image" src="https://github.com/ErHaWeb/klaro_consent_manager/assets/2393228/ce3c3e28-bf85-4292-b29b-160e39b378c6">

**My "problem" no.2:**
Additionally the headline which often/normally contains the title of the video is invisible until accepting Youtube, so there is no information what will be shown and we lack a very important trigger/motivation to click and accept. 

**Idea for a solution:**

1. Get the CE's title and place it above the video placeholder or check respect the CE's layout settings. I guess the second idea is more complex. 
2. Get the thumbnail from the video which is normally stored locally the first time grabbing the video URL. This would give us the at least the right aspect ratio an be able to use a Bootstrap card overlay wrapping:  [https://getbootstrap.com/docs/5.3/components/card/](url)
<img width="1006" alt="image" src="https://github.com/ErHaWeb/klaro_consent_manager/assets/2393228/8f24da24-937c-4eeb-a38e-3c47179f70a7">
3. Maybe an integrator could add a custom Fluid template to wrap the placeholder which would probably offer most of what is needed for sloving this without getting too deep into coding?

What do you think?

**Comment by ErHaWeb** [comment]
Thank you for your feedback.

**Problem 1:**
Regarding your problem with the height of the contextual consent box, I am still working on a solution. The difficulty here is that the box is dynamically generated by the default Klaro script and I have no direct control over it. I am thinking about recompiling the Klaro script with the necessary changes to allow templating via fluid.

For now, it may be sufficient to select the Contextual Consent Box using the data-name attribute. For the YouTube service, the necessary (S)CSS for a 16:9 aspect ratio should look something like this:

**SCSS**
```scss
[data-type="placeholder"] {
  &[data-name="youtube"] {
    height: 0;
    padding: 0 0 56.25%;
    position: relative;

    > .cm-as-context-notice {
      position: absolute;
      top: 0;
      right: 0;
      bottom: 0;
      left: 0;
      height: 100%;
      width: 100%;
    }
  }
}
```
or simple **CSS**
```css
data-type=placeholder][data-name=youtube] {
  height: 0;
  padding: 0 0 56.25%;
  position: relative;
}

[data-type=placeholder][data-name=youtube] > .cm-as-context-notice {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  height: 100%;
  width: 100%;
}
```

**Problem 2:**
Regarding your problem with the headings: In the feature release released today, the heading is kept by default. In addition, it is possible to specify whether headings should also be included in the Contextual Consent Box using the following TypoScript constant:

```typoscript
plugin.tx_klaroconsentmanager.settings.contextualconsent.mainSectionOnly = 1
```
Values:
0 = All content (except the frame) is enclosed in the Contextual Consent Box.
1 = Only the main content is enclosed in the Contextual Consent Box.

**Caution**
Please note that the Klaro extension extends the default layout of EXT:fluid_styled_content (`EXT:fluid_styled_content/Resources/Private/Layouts/Default.html`) to make the above distinction. If you have already overridden this layout in your integration, you will need to manually insert the Klaro extension changes there.

--

I hope this info helps you for now.

**Comment by hilburger** [comment]
Thank you Eric! 
I have had solved this with a Bootstrap (5) class which basically does just the same like your code:

```SCSS
div[data-type="placeholder"] {
  .klaro.cm-as-context-notice {
    @extend .ratio;
    @extend .ratio-16x9;
    margin-bottom: var(--contentcontainer-gap);
    padding: 0;

    .context-notice {
      border-radius: inherit;
      border: none;

    }
  }
}
```

I will test the new version with headline handling now! :)
